kaitoss/Areas/Admin/Controllers/BlogController.cs
using kaitoss.Data;
using kaitoss.Data.Models;
using kaitoss.IRepostiory;
using kaitoss.Services.File;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace kaitoss.Areas.Admin.Controllers
{
    public class BlogController : BaseController
    {
        private readonly IBlogRepo _BlogRepo;
        private readonly IFileSevices _fileSevices;
        private readonly ApplicationDbContext _context;
        public BlogController(IBlogRepo BlogRepo, IFileSevices fileSevices, ApplicationDbContext context)
        {
            _BlogRepo = BlogRepo;
            _fileSevices = fileSevices;
            _context= context;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _BlogRepo.GetAll());
        }
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _BlogRepo.GetById(id));
        }
        public async Task<IActionResult> Create()
        {
            ViewData["UserID"] = new SelectList(_context.Users.ToList(), "Id", "Email");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Blog model,IFormFile file)
        {

            model.Logo = await _fileSevices.UploadImageAsync(file);
            await _BlogRepo.Add(model);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _BlogRepo.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Blog model)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _BlogRepo.Update(id, model);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _BlogRepo.GetById(id));
        }
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _BlogRepo.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

kaitoss/Areas/Admin/Controllers/CategoryController.cs
using kaitoss.Data.Models;
using kaitoss.IRepostiory;
using Microsoft.AspNetCore.Mvc;

namespace kaitoss.Areas.Admin.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoryRepo _categoryRepo;

        public CategoryController(ICategoryRepo categoryRepo)
        {
            _categoryRepo = categoryRepo;
        }
        public async Task< IActionResult> Index()
        {
            
            return View(await _categoryRepo.GetAll());
        }
        public async Task<IActionResult> Details(int id)
        {
            if (id==null)
            {
                return NotFound();
            }
            return View( await _categoryRepo.GetById(id));
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category model)
        {
            if (ModelState.IsValid)
            {
               await _categoryRepo.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> Edit(int  id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _categoryRepo.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Category model)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _categoryRepo.Update(id, model);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _categoryRepo.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _categoryRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

kaitoss/Areas/Admin/Controllers/ServicesController.cs
using kaitoss.Data.Models;
using kaitoss.IRepostiory;
using kaitoss.Services.File;
using Microsoft.AspNetCore.Mvc;

namespace kaitoss.Areas.Admin.Controllers
{
    public class ServicesController : BaseController
    {
        private readonly IServicesRepo _ServicesRepo;
        private readonly IFileSevices _fileSevices;

        public ServicesController(IServicesRepo ServicesRepo, IFileSevices fileSevices)
        {
            _ServicesRepo = ServicesRepo;
            _fileSevices = fileSevices;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _ServicesRepo.GetAll());
        }
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _ServicesRepo.GetById(id));
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(kaitoss.Data.Models.Services model, IFormFile file)
        {
            model.Logo = await _fileSevices.UploadImageAsync(file);
            await _ServicesRepo.Add(model);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _ServicesRepo.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, kaitoss.Data.Models.Services model)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _ServicesRepo.Update(id, model);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _ServicesRepo.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _ServicesRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }

}

kaitoss/Areas/Admin/Controllers/SettingsController.cs
using kaitoss.Data.Models;
using kaitoss.IRepostiory;
using Microsoft.AspNetCore.Mvc;

namespace kaitoss.Areas.Admin.Controllers
{
    public class SettingsController : BaseController
    {
        private readonly ISettingsRepo _SettingsRepo;

        public SettingsController(ISettingsRepo SettingsRepo)
        {
            _SettingsRepo = SettingsRepo;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _SettingsRepo.GetAll());
        }
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _SettingsRepo.GetById(id));
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Settings model)
        {
          
               await _SettingsRepo.Add(model);
                return RedirectToAction("Index");
            
        }
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _SettingsRepo.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Settings model)
        {
            if (id == null)
            {
                return NotFound();
            }
           await _SettingsRepo.Update(id, model);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _SettingsRepo.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _SettingsRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

kaitoss/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kaitoss</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/kaitoss.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">kaitoss</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Services" asp-action="Index">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Settings" asp-action="Index">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                   
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - kaitoss - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>